title: Capstone Project
logo: /assets/img/uh_logo.png
description: Technology for learning. Capstone project for CUIN XXXX by Daniel Burgos at the Univeristy of Houston.  
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
