title: Capstone Project
logo: /assets/img/uh_logo.png
description: Master’s LDT Capstone Website by Daniel Burgos at the University of Houston.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
